services:
    Kaliber5\SettingsBundle\Admin\SettingAdmin:
        arguments: [~, Kaliber5\SettingsBundle\Entity\Setting, ~]
        calls:
            - setSettingTypeProvider: ['@Kaliber5\SettingsBundle\Provider\SettingTypeProvider']
        tags:
            - { name: sonata.admin, manager_type: orm, group: Einstellungen, label: Setting , icon: <i class="fa fa-cog"></i>}

    Kaliber5\SettingsBundle\Admin\SettingValueAdmin:
        arguments: [~, Kaliber5\SettingsBundle\Entity\SettingValue, ~]
        calls:
            -   setSettingTypeProvider: [ '@Kaliber5\SettingsBundle\Provider\SettingTypeProvider' ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Einstellungen, label: SettingValue , icon: <i class="fa fa-cog"></i>, show_in_dashboard: false}
